### ISSUE TITLE
PHP 7.1 intval fix

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xftheme-issues#63] opened 2017-03-02 20:17 UTC
When you do something like {xen:calc '@styleProperty + 12’}

everything like that needs to be changed to:

{xen:calc ‘intval(@styleProperty) + 12’}

**Comment by JakeBooher** [comment] 2017-03-10 19:50
Duplicate of #16

**Closed by JakeBooher** 2017-03-10 19:50 UTC
Labels: Duplicate, UI.X
