### ISSUE TITLE
Reneue: PHP 7.1 - A non-numeric value encountered

### ISSUE THREAD

**Issue by ThomasTr** [Audentio/xftheme-issues#60] opened 2017-02-24 18:32 UTC
Since Update to PHP 7.1 i get tons of these errors:

A non-numeric value encountered:

'CSS Error: PHP: <div class=baseHtml><h4>Template Errors: uix.css</h4><ol>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 6: <pre>5: $headerTabHeight_outer = ;6: $headerTabHeight_outer .= (XenForo_Template_Helper_Core::styleProperty(headerTabHeight) + XenForo_Template_Helper_Core::styleProperty(navTabs.border-top-width) + XenForo_Template_Helper_Core::styleProperty(navTabs.border-bottom-width) + XenForo_Template_Helper_Core::styleProperty(navTabs.padding-top) + XenForo_Template_Helper_Core::styleProperty(navTabs.padding-bottom));7: $__output .= </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 6: <pre>5: $headerTabHeight_outer = ;6: $headerTabHeight_outer .= (XenForo_Template_Helper_Core::styleProperty(headerTabHeight) + XenForo_Template_Helper_Core::styleProperty(navTabs.border-top-width) + XenForo_Template_Helper_Core::styleProperty(navTabs.border-bottom-width) + XenForo_Template_Helper_Core::styleProperty(navTabs.padding-top) + XenForo_Template_Helper_Core::styleProperty(navTabs.padding-bottom));7: $__output .= </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 6: <pre>5: $headerTabHeight_outer = ;6: $headerTabHeight_outer .= (XenForo_Template_Helper_Core::styleProperty(headerTabHeight) + XenForo_Template_Helper_Core::styleProperty(navTabs.border-top-width) + XenForo_Template_Helper_Core::styleProperty(navTabs.border-bottom-width) + XenForo_Template_Helper_Core::styleProperty(navTabs.padding-top) + XenForo_Template_Helper_Core::styleProperty(navTabs.padding-bottom));7: $__output .= </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 10: <pre>9: $uix_fixedNavigationHeight_outer = ;10: $uix_fixedNavigationHeight_outer .= (XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigationHeight) + XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigation_style.border-top-width) + XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigation_style.border-bottom-width) + XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigation_style.padding-top) + XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigation_style.padding-bottom));11: $__output .= </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 10: <pre>9: $uix_fixedNavigationHeight_outer = ;10: $uix_fixedNavigationHeight_outer .= (XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigationHeight) + XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigation_style.border-top-width) + XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigation_style.border-bottom-width) + XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigation_style.padding-top) + XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigation_style.padding-bottom));11: $__output .= </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 10: <pre>9: $uix_fixedNavigationHeight_outer = ;10: $uix_fixedNavigationHeight_outer .= (XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigationHeight) + XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigation_style.border-top-width) + XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigation_style.border-bottom-width) + XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigation_style.padding-top) + XenForo_Template_Helper_Core::styleProperty(uix_fixedNavigation_style.padding-bottom));11: $__output .= </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 15: <pre>14: $uix_tabLinksHeight_outer = ;15: $uix_tabLinksHeight_outer .= (XenForo_Template_Helper_Core::styleProperty(uix_tabLinksHeight) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinks_style.padding-top) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinks_style.padding-bottom) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinks_style.border-bottom-width) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinks_style.border-top-width));16: $__output .= </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 15: <pre>14: $uix_tabLinksHeight_outer = ;15: $uix_tabLinksHeight_outer .= (XenForo_Template_Helper_Core::styleProperty(uix_tabLinksHeight) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinks_style.padding-top) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinks_style.padding-bottom) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinks_style.border-bottom-width) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinks_style.border-top-width));16: $__output .= </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 15: <pre>14: $uix_tabLinksHeight_outer = ;15: $uix_tabLinksHeight_outer .= (XenForo_Template_Helper_Core::styleProperty(uix_tabLinksHeight) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinks_style.padding-top) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinks_style.padding-bottom) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinks_style.border-bottom-width) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinks_style.border-top-width));16: $__output .= </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 19: <pre>18: $uix_tabLinksHeightSticky_outer = ;19: $uix_tabLinksHeightSticky_outer .= (XenForo_Template_Helper_Core::styleProperty(uix_tabLinksHeightSticky) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinksSticky_style.padding-top) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinksSticky_style.padding-bottom) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinksSticky_style.border-bottom-width) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinksSticky_style.border-top-width));20: $__output .= </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 19: <pre>18: $uix_tabLinksHeightSticky_outer = ;19: $uix_tabLinksHeightSticky_outer .= (XenForo_Template_Helper_Core::styleProperty(uix_tabLinksHeightSticky) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinksSticky_style.padding-top) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinksSticky_style.padding-bottom) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinksSticky_style.border-bottom-width) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinksSticky_style.border-top-width));20: $__output .= </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 19: <pre>18: $uix_tabLinksHeightSticky_outer = ;19: $uix_tabLinksHeightSticky_outer .= (XenForo_Template_Helper_Core::styleProperty(uix_tabLinksHeightSticky) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinksSticky_style.padding-top) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinksSticky_style.padding-bottom) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinksSticky_style.border-bottom-width) + XenForo_Template_Helper_Core::styleProperty(uix_tabLinksSticky_style.border-top-width));20: $__output .= </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 2933: <pre>2932: $__compilerVar7 .= 2933: 			padding-right:  . (XenForo_Template_Helper_Core::styleProperty(uix_searchButtonStyle.width) + XenForo_Template_Helper_Core::styleProperty(uix_quickSearchStyle.padding-right)) . px;2934: 		;</pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 4438: <pre>4437: $uix_pageNavItemLineHeight = ;4438: $uix_pageNavItemLineHeight .= (XenForo_Template_Helper_Core::styleProperty(uix_pageNav_height) - XenForo_Template_Helper_Core::styleProperty(pageNavItem.border-top-width) - XenForo_Template_Helper_Core::styleProperty(pageNavItem.border-bottom-width) - XenForo_Template_Helper_Core::styleProperty(pageNavItem.padding-top) - XenForo_Template_Helper_Core::styleProperty(pageNavItem.padding-bottom));4439: $__output .= </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 4438: <pre>4437: $uix_pageNavItemLineHeight = ;4438: $uix_pageNavItemLineHeight .= (XenForo_Template_Helper_Core::styleProperty(uix_pageNav_height) - XenForo_Template_Helper_Core::styleProperty(pageNavItem.border-top-width) - XenForo_Template_Helper_Core::styleProperty(pageNavItem.border-bottom-width) - XenForo_Template_Helper_Core::styleProperty(pageNavItem.padding-top) - XenForo_Template_Helper_Core::styleProperty(pageNavItem.padding-bottom));4439: $__output .= </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 5065: <pre>5064: .breadcrumb .jumpMenuTrigger {5065: 	line-height:  . (XenForo_Template_Helper_Core::styleProperty(breadcrumb.height) - (XenForo_Template_Helper_Core::styleProperty(breadcrumb.border-top-width) + XenForo_Template_Helper_Core::styleProperty(breadcrumb.border-bottom-width))) . px;5066: }</pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 5065: <pre>5064: .breadcrumb .jumpMenuTrigger {5065: 	line-height:  . (XenForo_Template_Helper_Core::styleProperty(breadcrumb.height) - (XenForo_Template_Helper_Core::styleProperty(breadcrumb.border-top-width) + XenForo_Template_Helper_Core::styleProperty(breadcrumb.border-bottom-width))) . px;5066: }</pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 5084: <pre>5083: .breadcrumb .crust {5084: 	line-height:  . (XenForo_Template_Helper_Core::styleProperty(breadcrumb.height) - (XenForo_Template_Helper_Core::styleProperty(breadcrumb.border-top-width) + XenForo_Template_Helper_Core::styleProperty(breadcrumb.border-bottom-width))) . px;5085: }</pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 5084: <pre>5083: .breadcrumb .crust {5084: 	line-height:  . (XenForo_Template_Helper_Core::styleProperty(breadcrumb.height) - (XenForo_Template_Helper_Core::styleProperty(breadcrumb.border-top-width) + XenForo_Template_Helper_Core::styleProperty(breadcrumb.border-bottom-width))) . px;5085: }</pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 5131: <pre>5130: 	height:  . XenForo_Template_Helper_Core::styleProperty(breadcrumb.height) . ;5131: 	line-height:  . (XenForo_Template_Helper_Core::styleProperty(breadcrumb.height) - XenForo_Template_Helper_Core::styleProperty(breadcrumb.border-top-width) - XenForo_Template_Helper_Core::styleProperty(breadcrumb.border-bottom-width)) . px;5132: </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 5131: <pre>5130: 	height:  . XenForo_Template_Helper_Core::styleProperty(breadcrumb.height) . ;5131: 	line-height:  . (XenForo_Template_Helper_Core::styleProperty(breadcrumb.height) - XenForo_Template_Helper_Core::styleProperty(breadcrumb.border-top-width) - XenForo_Template_Helper_Core::styleProperty(breadcrumb.border-bottom-width)) . px;5132: </pre></li>	<li><i>A non-numeric value encountered</i> in /private/var/www/tfx/public/library/XenForo/Template/Abstract.php(265) : eval()d code, line 6487: <pre>6486: .node .nodeControls {6487: 	right:  . (XenForo_Template_Helper_Core::styleProperty(nodeLastPost.width) + XenForo_Template_Helper_Core::styleProperty(nodeLastPost.margin-right) + XenForo_Template_Helper_Core::styleProperty(nodeLastPost.margin-left)) . px;6488: }</pre></li></ol></div>'

**Comment by JakeBooher** [comment] 2017-02-24 19:11
For the most part, this is a duplicate of #16 Unfortunately no ETA on a fix currently as there are a ton of changes that need to be made to get it working 100%, though this is just a warning, not an actual error, so disabling Debug mode in XenForo should hide this for you :)

**Closed by JakeBooher** 2017-02-24 19:11 UTC
